Fixes for Windows and Travis

diff --git a/.travis.yml b/.travis.yml
--- a/.travis.yml
+++ b/.travis.yml
@@ -21,22 +21,22 @@ matrix:
         - os: linux
           env:
           - BUILD_TYPE=Debug CFG="monotonic openssl werror"
-          - BUILD_OPTS='-DENABLE_BONDING=ON -DCMAKE_CXX_FLAGS="-Werror"'
+          - CMAKE_OPTS='-DENABLE_BONDING=ON -DCMAKE_CXX_FLAGS="-Werror"'
         - env:
           - BUILD_TYPE=Debug CFG="nologging mbedtls monotonic werror"
-          - BUILD_OPTS='-DENABLE_LOGGING=OFF -DUSE_ENCLIB=mbedtls -DENABLE_MONOTONIC_CLOCK=ON -DENABLE_BONDING=ON -DCMAKE_CXX_FLAGS="-Werror"'
+          - CMAKE_OPTS='-DENABLE_LOGGING=OFF -DUSE_ENCLIB=mbedtls -DENABLE_MONOTONIC_CLOCK=ON -DENABLE_BONDING=ON -DCMAKE_CXX_FLAGS="-Werror"'
         - os: linux
           env: BUILD_TYPE=Release CFG=default
 #       - os: osx
 #         osx_image: xcode11.1
 #         env:
 #         - BUILD_TYPE=Debug CFG=werror
-#         - BUILD_OPTS='-DCMAKE_CXX_FLAGS="-Werror"'
+#         - CMAKE_OPTS='-DCMAKE_CXX_FLAGS="-Werror"'
 #       - os: osx
 #         osx_image: xcode11.1
 #         env:
 #         - BUILD_TYPE=Release CFG=werror
-#         - BUILD_OPTS='-DCMAKE_CXX_FLAGS="-Werror"'
+#         - CMAKE_OPTS='-DCMAKE_CXX_FLAGS="-Werror"'
         - os: linux
           compiler: x86_64-w64-mingw32-g++
           addons:
@@ -63,31 +63,39 @@ matrix:
         - arch: ppc64le
           env:
           - BUILD_TYPE=Release CFG=monotonic
-          - BUILD_OPTS='-DENABLE_MONOTONIC_CLOCK=ON'
+          - CMAKE_OPTS='-DENABLE_MONOTONIC_CLOCK=ON'
 script:
+    - cmake --version | head -1
+    - export REQUIRE_UNITTESTS=1
+    - if [ "$TRAVIS_COMPILER" == "x86_64-w64-mingw32-g++" ]; then
+        CMAKE_OPTS+=" -DCMAKE_C_COMPILER=x86_64-w64-mingw32-gcc";
+        CMAKE_OPTS+=" -DCMAKE_CXX_COMPILER=x86_64-w64-mingw32-g++";
+        CMAKE_OPTS+=" -DENABLE_STDCXX_SYNC=OFF -DENABLE_UNITTESTS=OFF -DUSE_OPENSSL_PC=OFF";
+        CMAKE_OPTS+=" -DOPENSSL_ROOT_DIR=\"$PWD/openssl\"";
+        CMAKE_OPTS+=" -DCMAKE_SYSTEM_NAME=Windows";
+        REQUIRE_UNITTESTS=0;
+      fi
+#     if [ "$TRAVIS_OS_NAME" == "osx" ]; then
+#       export PKG_CONFIG_PATH=$(brew --prefix openssl)"/lib/pkgconfig";
+#     fi
+      if (( $REQUIRE_UNITTESTS )); then
+        CMAKE_OPTS+=" -DENABLE_UNITTESTS="ON";
+      fi
     - echo COMPILER $TRAVIS_COMPILER
     - echo SYSTEM $TRAVIS_OS_NAME
     - echo BUILD_TYPE $BUILD_TYPE
-    - echo BUILD_OPTS $BUILD_OPTS
-    - cmake --version | head -1
-    - if [ "$TRAVIS_COMPILER" == "x86_64-w64-mingw32-g++" ]; then
-        BUILD_OPTS+=" -DCMAKE_C_COMPILER=x86_64-w64-mingw32-gcc";
-        BUILD_OPTS+=" -DCMAKE_CXX_COMPILER=x86_64-w64-mingw32-g++";
-        BUILD_OPTS+=" -DENABLE_STDCXX_SYNC=OFF -DENABLE_UNITTESTS=OFF -DUSE_OPENSSL_PC=OFF";
-        BUILD_OPTS+=" -DOPENSSL_ROOT_DIR=\"$PWD/openssl\"";
-        BUILD_OPTS+=" -DCMAKE_SYSTEM_NAME=Windows";
-      elif [ "$TRAVIS_OS_NAME" == "linux" ]; then
-        BUILD_OPTS+=" -DENABLE_UNITTESTS="ON";
-      elif [ "$TRAVIS_OS_NAME" == "osx" ]; then
-        export PKG_CONFIG_PATH=$(brew --prefix openssl)"/lib/pkgconfig";
-        BUILD_OPTS+=" -DENABLE_UNITTESTS="ON";
-      fi
-    - if cmake . -DCMAKE_BUILD_TYPE=$BUILD_TYPE $BUILD_OPTS $CMAKE_OPTS; then echo "Configure OK"; else cat CMakeFiles/CMakeError.log; fi;
+    - echo CMAKE_OPTS $CMAKE_OPTS
+    - if cmake . -DCMAKE_BUILD_TYPE=$BUILD_TYPE $CMAKE_OPTS; then echo "Configure OK"; else cat CMakeFiles/CMakeError.log; exit 1; fi;
     - make VERBOSE=1 -j$(nproc);
-    - if [ "$TRAVIS_COMPILER" != "x86_64-w64-mingw32-g++" ]; then
+    - if (( $REQUIRE_UNITTESTS )); then
         ulimit -c unlimited;
-        ./test-srt -disable-ipv6;
-        SUCCESS=$?;
-        if [ -f core ]; then gdb -batch ./test-srt -c core -ex bt -ex "info thread" -ex quit; else echo "NO CORE - NO CRY!"; fi;
-        test $SUCCESS == 0;
+        if [ ! -f ./test-srt ]; then
+          echo "ERROR: UT application not found";
+          test 1 == 0;
+        else
+          ./test-srt -disable-ipv6;
+          SUCCESS=$?;
+          if [ -f core ]; then gdb -batch ./test-srt -c core -ex bt -ex "info thread" -ex quit; else echo "NO CORE - NO CRY!"; fi;
+          test $SUCCESS == 0;
+        fi
       fi
