[DEV] Updated ABI checker to use correct version ABI checks.

diff --git a/.github/workflows/abi.yml b/.github/workflows/abi.yml
--- a/.github/workflows/abi.yml
+++ b/.github/workflows/abi.yml
@@ -17,45 +17,48 @@ jobs:
     steps:
     - uses: actions/checkout@v3
       with:
-        path: pull_request
+        path: gitview_pr
     - name: configure
       run: |
-        cd pull_request
+        cd gitview_pr
         mkdir _build && cd _build
         cmake -DCMAKE_BUILD_TYPE=Debug -DENABLE_UNITTESTS=ON ../
     - name: build
       run: |
-        sudo apt install -y abi-dumper
-        cd pull_request/_build && cmake --build ./
+        sudo apt install -y abi-dumper tcl
+        cd gitview_pr/_build && cmake --build ./
         make install DESTDIR=./installdir
-        SRT_TAG_VERSION=$(cat version.h |grep SRT_VERSION_MINOR |head -n1 |awk {'print $3'})
-        abi-dumper libsrt.so -o libsrt-pr.dump -public-headers installdir/usr/local/include/srt/ -lver 0
-        SRT_BASE="v1.$SRT_TAG_VERSION.0"
+        SRT_TAG_VERSION=v$(../scripts/get-build-version.tcl full)
+		SRT_BASE=v$(../scripts/get-build-version.tcl base)
+        abi-dumper libsrt.so -o libsrt-pr.dump -public-headers installdir/usr/local/include/srt/ -lver $SRT_TAG_VERSION
         echo "SRT_BASE=$SRT_BASE" >> "$GITHUB_ENV"
     - uses: actions/checkout@v3
       with:
-        path: tag
+        path: gitview_base
         ref: ${{ env.SRT_BASE }}
     - name: configure_tag
       run: |
         echo $SRT_TAG_VERSION
-        cd tag
+        cd gitview_base
         mkdir _build && cd _build
         cmake -DCMAKE_BUILD_TYPE=Debug -DENABLE_UNITTESTS=ON ../
     - name: build_tag
       run: |
-        cd tag      
+        cd gitview_base      
         cd _build && cmake --build ./
         make install DESTDIR=./installdir
-        abi-dumper libsrt.so -o libsrt-tag.dump -public-headers installdir/usr/local/include/srt/ -lver 1
+        abi-dumper libsrt.so -o libsrt-base.dump -public-headers installdir/usr/local/include/srt/ -lver $SRT_BASE
     - name: abi-check
       run: |
-         git clone https://github.com/lvc/abi-compliance-checker.git
-         cd abi-compliance-checker && sudo make install && cd ../
-         abi-compliance-checker -l libsrt -old tag/_build/libsrt-tag.dump -new pull_request/_build/libsrt-pr.dump
-         RES=$?
-         if (( $RES != 0 ))
-          then
-            echo "ABI/API Compatibility check failed with value $?"
-            exit $RES
-          fi
+		 if [[$SRT_TAG_VERSION == $SRT_BASE]]; then
+			echo "NO CHECKS DONE: PR is still the base version $SRT_BASE"
+		 else
+			 #git clone https://github.com/lvc/abi-compliance-checker.git
+			 cd submodules/abi-compliance-checker && sudo make install && cd ../
+			 abi-compliance-checker -l libsrt -old gitview_base/_build/libsrt-base.dump -new gitview_pr/_build/libsrt-pr.dump
+			 RES=$?
+			 if (( $RES != 0 )); then
+				echo "ABI/API Compatibility check failed with value $?"
+				exit $RES
+			 fi
+		 fi
